version: '3.8'

services:
  express:
    build: 
      context: ./express
      dockerfile: ./Dockerfile
    env_file:
      - .env-dev
    ports:
      - "3000:3000"
    volumes:
      - ./express:/usr/src/app
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env-dev
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
