version: '3.8'

services:
  express:
    build: 
      context: ./express
      dockerfile: ./Dockerfile
    env_file:
      - .env-dev
    ports:
      - "3000:3000"
    volumes:
      - ./express:/usr/src/app
  postgres:
    image: postgres:latest
    env_file:
      - .env-dev
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    env_file:
      - .env-dev
    ports:
      - "8888:80"
